spring.application.name=NeptuneWebAutheticator
spring.output.ansi.enabled=ALWAYS
spring.datasource.url=jdbc:mariadb://localhost:3306/AuthenticationService
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jackson.property-naming-strategy=UPPER_CAMEL_CASE
spring.mvc.contentnegotiation.media-types.json=application/json
spring.mvc.contentnegotiation.media-types.plain=text/plain
spring.jpa.open-in-view=false
hibernate.dialect=org.hibernate.dialect.MariaDBDialect
server.port=8080
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
